///////////////////////////////////////////////////////////
//  Admin.cs
//  Implementation of the Class Admin
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:25 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Admin {

		private string id;

		public Admin(){

		}

		~Admin(){

		}

		public void login(){

		}

		public void manageBooking(){

		}

	}//end Admin

}//end namespace Application