///////////////////////////////////////////////////////////
//  BookingAdapter.cs
//  Implementation of the Class BookingAdapter
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:28 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public class BookingAdapter {

		private int facilityName;
		private int ManageBooking book;

		public BookingAdapter(){

		}

		~BookingAdapter(){

		}

		public void display(){

		}

	}//end BookingAdapter

}//end namespace Application