///////////////////////////////////////////////////////////
//  Booking.cs
//  Implementation of the Class Booking
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:26 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public class Booking {

		private int amount;
		private string date;
		private string facilityName;
		private string paymentType;
		private string purpose;
		private Online Banking m_Online Banking;
		private Application.User m_User;

		public Booking(){

		}

		~Booking(){

		}

		public void BookFacility(){

		}

		public void display(){

		}

		public Online Banking Online Banking{
			get{
				return m_Online Banking;
			}
			set{
				m_Online Banking = value;
			}
		}

		public void payment(){

		}

		public void update(){

		}

		public User User{
			get{
				return m_User;
			}
			set{
				m_User = value;
			}
		}

	}//end Booking

}//end namespace Application