///////////////////////////////////////////////////////////
//  BookingList.cs
//  Implementation of the Interface BookingList
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:29 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public interface BookingList  {

		display();
	}//end BookingList

}//end namespace Application