///////////////////////////////////////////////////////////
//  LoginAdmin.cs
//  Implementation of the Class LoginAdmin
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:32 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public class LoginAdmin : Register {

		private string email;
		private string password;
		private Application.Admin m_Admin;



		~LoginAdmin(){

		}

		public LoginAdmin(){

		}

		public Admin Admin{
			get{
				return m_Admin;
			}
			set{
				m_Admin = value;
			}
		}

	}//end LoginAdmin

}//end namespace Application