///////////////////////////////////////////////////////////
//  Online Banking.cs
//  Implementation of the Class Online Banking
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:36 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DAL;



namespace BLL {
	public class OnlineBanking {

		private int accNo;
		private string name;

        OnlineBankingDL objDAL = new OnlineBankingDL();

        public void OnlineBankingReg(int accNo , string name)
        {
            objDAL.InsertDataOB(accNo, name);
        }

		public  OnlineBanking(){

		}

		~OnlineBanking(){

		}

		public int checkAcc(){

			return 0;
		}

		public int DisplayMessage(){

			return 0;
		}

		public int enterAccInfo(){

			return 0;
		}

		public int enterAmount(){

			return 0;
		}

		public int validateTransaction(){

			return 0;
		}

	}//end Online Banking

}//end namespace Application