///////////////////////////////////////////////////////////
//  Parking.cs
//  Implementation of the Class Parking
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:37 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public class Parking : Vehicle {

		private double balance;
		private string plateNo;
		private string time;
		private string zone;
		private Application.User m_User;

		public Parking(){

		}

		~Parking(){

		}

		public void AddParking(){

		}

		public void DisplayMessage(){

		}

		public void payParking(){

		}

		public void selectVehicle(){

		}

		public User User{
			get{
				return m_User;
			}
			set{
				m_User = value;
			}
		}

	}//end Parking

}//end namespace Application