///////////////////////////////////////////////////////////
//  Register.cs
//  Implementation of the Class Register
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2019 10:44:13 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DAL;





namespace BLL {
	public class Register {
        private string email;
        private string password;

        RegisterDataLayer objDAL = new RegisterDataLayer();

        public void RegisterUser(string email, string password)
        {

            objDAL.InsertData(email, password);
        }

  
		public Register(){

		}

		~Register(){

		}

		

	}//end Register

}//end namespace Application