///////////////////////////////////////////////////////////
//  Reload.cs
//  Implementation of the Class Reload
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:40 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public class Reload : User, ReloadWallet {

		private int amount;
		private string bankName;
		private int phoneNo;
		private Online Banking m_Online Banking;

		public Reload(){

		}

		~Reload(){

		}

		public void notifyObserver(){

		}

		public Online Banking Online Banking{
			get{
				return m_Online Banking;
			}
			set{
				m_Online Banking = value;
			}
		}

		public void payment(){

		}

		public reload(){

		}

		public void success(){

		}
		
		public void unsuccess(){

		}


		public void successObserver(){

		}

		public void unsuccessObserver(){

		}

		public void updateBalance(){

		}

	}//end Reload

}//end namespace Application