///////////////////////////////////////////////////////////
//  ReloadWallet.cs
//  Implementation of the Interface ReloadWallet
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:42 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Application;
namespace Application {
	public interface ReloadWallet  {

		notifyObserver();

		successObserver();

		unsuccessObserver();
	}//end ReloadWallet

}//end namespace Application